# Generated by Django 5.2.5 on 2025-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/original/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/')),
                ('hls_dir', models.CharField(blank=True, max_length=255)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
